FROM python:3.11-slim
WORKDIR /app

# Paquetes útiles para healthcheck curl
RUN apt-get update && apt-get install -y --no-install-recommends curl && rm -rf /var/lib/apt/lists/*

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8082
CMD ["gunicorn", "-w", "2", "-b", "0.0.0.0:8082", "app:app"]
